ECommerce.Web/Controllers/CarroDeComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECommerce.Domain.AgregadoPedido;
using ECommerce.Domain.AgregadoProduto;

namespace ECommerce.Web.Controllers
{
    public class CarroDeComprasController : Controller
    {
        private IProdutoService _produtoService;
        private IPedidoService _pedidoService;

        public CarroDeComprasController(IProdutoService produtoService, IPedidoService pedidoService)
        {
            this._pedidoService = pedidoService;
            this._produtoService = produtoService;
        }

        public ActionResult AdicionarItem(CarroDeCompras carroDeCompras, int idProduto, int quantidade)
        {
            var produto = _produtoService.ObterTodosProdutos().First(x => x.Id == idProduto);
            carroDeCompras.AdicionarItemPedido(new ItemPedido() {Produto = produto, Quantidade = quantidade});
            TempData["Mensagem"] = "Produto adicionado com sucesso.";

            return RedirectToAction("Index", "Produto");
        }

        public ActionResult Index(CarroDeCompras carroDeCompras)
        {
            return View(carroDeCompras);
        }

        public ActionResult FinalizarCompra(CarroDeCompras carroDeCompras, string idFormaPagamento)
        {
            if (carroDeCompras.CompraPodeSerFinalizada())
            {
                var pedido = carroDeCompras.FinalizarCompra(FormaPagamento.ObterPorId(idFormaPagamento));
                _pedidoService.IncluirPedido(pedido);
                TempData["Mensagem"] = "Pedido realizado com sucesso.";
            } else
            {
                TempData["Mensagem"] = "Estoque insuficiente para sua compra.";
            }
            
            return RedirectToAction("Index");
        }


        public ActionResult RemoverProduto(CarroDeCompras carroDeCompras, string idProduto)
        {
            carroDeCompras.RemoverProduto(idProduto);
            TempData["Mensagem"] = "Produto removido com sucesso.";
            return View("Index", carroDeCompras);
        }
    }
}

ECommerce.Web/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECommerce.Domain.AgregadoProduto;

namespace ECommerce.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private IProdutoService _produtoService;

        public ProdutoController(IProdutoService produtoService)
        {
            this._produtoService = produtoService;
        }

        //
        // GET: /Produto/
        public ActionResult Index()
        {
            var listaProdutos = this._produtoService.ObterTodosProdutos().ToList();

            return View(listaProdutos);
        }
    }
}

ECommerce.Web/Views/CarroDeCompras/Index.cshtml
@using ECommerce.Domain.AgregadoPedido;
@model ECommerce.Domain.AgregadoPedido.CarroDeCompras
@{
    ViewBag.Title = "title";
}
<h2>
    Meu Carrinho de Compras</h2>
@foreach (var itemPedido in Model.ItensPedido)
{
    using (Html.BeginForm("RemoverProduto", "CarroDeCompras", FormMethod.Post))
    {
    <div>
        Produto: @itemPedido.Produto.Nome
        <br />
        Quantidade: @itemPedido.Quantidade
        <br />
        Preço: @itemPedido.Produto.Preco.ToString("N2")
        <br />
        Total: R$@itemPedido.CalcularPreco().ToString("N2")
        <br />
        
        @Html.Hidden("idProduto", itemPedido.Produto.Id)
        <input type="submit" value="Remover produto"/>
    </div>
    <br />    
    }
}
<div id="total">
    Total: R$@Model.CalcularPreco().ToString("N2")
</div>
@using (Html.BeginForm("FinalizarCompra", "CarroDeCompras"))
{
    <div id="formaPagamento">
        <br />
        @Html.RadioButton(name: "idFormaPagamento", value: FormaPagamento.Boleto.Id, isChecked: true)
        <span>@FormaPagamento.Boleto.Nome</span>
        <br />
        @Html.RadioButton(name: "idFormaPagamento", value: FormaPagamento.CartaoCreditoMaster.Id)
        <span>@FormaPagamento.CartaoCreditoMaster.Nome</span>
        <br />
        @Html.RadioButton(name: "idFormaPagamento", value: FormaPagamento.CartaoCreditoVisa.Id)
        <span>@FormaPagamento.CartaoCreditoVisa.Nome</span>
        <br />
    </div>

    <div>
        <br />
        <input type="submit" value="Finalizar Pedido" />
    </div>
}
<div id="mensagem">
    <br />
    @TempData["Mensagem"]
    <br />
</div>

ECommerce.Web/Views/Produto/Index.cshtml
@model List<ECommerce.Domain.AgregadoProduto.Produto>
@{
    ViewBag.Title = "Index";
}
<h3>
    Lista de Produtos</h3>
@foreach (var produto in Model)
{
    using (Html.BeginForm("AdicionarItem", "CarroDeCompras", FormMethod.Post))
    {
    <div>
        @Html.Hidden("idProduto", produto.Id)
        Nome: @produto.Nome
        <br />
        Quantidade em Estoque: @produto.QuantidadeEmEstoque
        <br />
        Preço: R$@produto.Preco.ToString("N2")
        <br />
        Quantidade:
        @Html.TextBox("quantidade", string.Empty, new { @type = "number", required = "required", pattern = "\\d+" })
        <br/>
        <input type="submit" value="Adicionar ao carrinho" />
    </div>
    <br />
    }
}

<div id="mensagem">
    <br />
    @TempData["Mensagem"]
    <br />
</div>

ECommerce.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>

<body>
    <div id="menu">
        <ul>
            <li>@Html.ActionLink("Produtos","Index","Produto")</li>
            <li>@Html.ActionLink("Meu Carrinho","Index","CarroDeCompras")</li>
        </ul>
    </div>
    @RenderBody()
</body>
</html>